### ISSUE TITLE
Dati normalizzati

### ISSUE THREAD

**Issue by pigreco** [ludovico85/webmap-COVID-19-Italia#1]
Ciao e grazie per la condivisione.

I dati che visualizzo nel pop-up della webmap sono dati assoluti, giusto??

Potreste aggiungere i dati normalizzati, per esempio `(valore/popolazione)*10.000 abitanti` in modo da leggere l'incidenza reale per ogni regione??

![image](https://user-images.githubusercontent.com/7631137/76702567-0070ad00-66cb-11ea-8eb2-04a19dd291ae.png)

Ottimo lavoro!

**Comment by ludovico85** [comment]
Certo, bella idea, direttamente nel pop-up.
Per i casi totali, gli attualmente positivi, si può fare l'incidenza per popolazione; per i decessi si può fare l'incidenza sui totali così come per i guariti. Cosa ne pensi?

**Comment by pigreco** [comment]
@ludovico85 penso che i valori assoluti non diano la corretta ed immediata giusta informazione.

**Comment by ludovico85** [comment]
![Cattura](https://user-images.githubusercontent.com/24815399/76746013-1b98f680-6777-11ea-9aae-49de3c0944d1.PNG)
![Cattura2](https://user-images.githubusercontent.com/24815399/76746025-20f64100-6777-11ea-8615-b3b05acabc58.PNG)


Può andare?

**Comment by pigreco** [comment]
@ludovico85 
se non erro la popolazione della Lombardia è di circa 10.000.000 abitanti, quindi

(13272/10000000)*10.000 abitanti = 13,272

cioè ci sono 13,272 casi totali ogni 10k abitanti

io la interpreterei cosi.

**Comment by ludovico85** [comment]
si è il modo giusto di interpretare il dato
